### ISSUE TITLE
Cpf.Validate retorna true, mesmo quando a string tem caracteres a mais

### ISSUE THREAD

**Issue by potchy** [aueda/maoli#19]
O CPF 58666979046**999** (coloquei três 9s a mais, no final), por exemplo, é inválido e mesmo assim a função `Cpf.Validate` retorna `true`. Não sei se esse comportamento é intencional, mas achei estranho. Estranhamente, parece que a validação de CEP é a única que considera a quantidade de caracteres.

 Exemplo:

```C#
using System;
using Maoli;
					
public class Program
{
	public static void Main()
	{
		var cpfs = new[] {
			"58666979046", // válido
			"58666979046999", // inválido?
			"586.669.790-46.999", // inválido?
		};
		
		foreach (string cpf in cpfs)
			Console.WriteLine("CPF {0} é válido? {1}", cpf, Cpf.Validate(cpf) ? "SIM" : "NÃO");
		
		var cnpjs = new[] {
			"12658591000178", // válido
			"12658591000178999", // inválido
			"12.658.591/0001-78.999", // inválido
		};
		
		foreach (string cnpj in cnpjs)
			Console.WriteLine("CNPJ {0} é válido? {1}", cnpj, Cnpj.Validate(cnpj) ? "SIM" : "NÃO");
		
		var ceps = new[] {
			"58088650",
			"580886500",
			"58088-650-99"
		};
		
		foreach (string cep in ceps)
			Console.WriteLine("CEP {0} é válido? {1}", cep, Cep.Validate(cep) ? "SIM" : "NÃO");
	}
}
```

Resultado:
- CPF 58666979046 é válido? SIM
- CPF 58666979046999 é válido? SIM
- CPF 586.669.790-46.999 é válido? SIM
- CNPJ 12658591000178 é válido? SIM
- CNPJ 12658591000178999 é válido? SIM
- CNPJ 12.658.591/0001-78.999 é válido? SIM
- CEP 58088650 é válido? SIM
- CEP 580886500 é válido? NÃO
- CEP 58088-650-99 é válido? NÃO

No .NET Fiddle: https://dotnetfiddle.net/lZluRC

**Comment by aueda** [comment]
Hey @potchy,

Obrigado pelo feedback.

Tem dois fatores que causam esse bug:

- Um bug na expressão regular
- O número é composto de um número válido com dígitos extras

Este foi resolvido com a reescrita que eu tinha feito há algum tempo mas não tinha publicado ainda. Também existe um teste para o número extra longo, mas ele não considera o caso do número conter um número válido.

Eu publiquei uma nova versão que resolve este bug: https://www.nuget.org/packages/Maoli/0.4.0

Esse fiddle já com a versão nova está validando corretamente: https://dotnetfiddle.net/kTZyAH

Teste novamente com esta versão por favor.

**Comment by potchy** [comment]
Obrigado pela resposta rápida.
Testei aqui e deu certo, valeu. 😄

Você pode me dizer qual foi o commit que resolveu esse problema, se ainda lembrar?

**Comment by aueda** [comment]
De nada @potchy !

O commit foi esse aqui: https://github.com/aueda/maoli/commit/f4aaad4e76a6141b77a5b8a175d93f3a76524ccb

Na verdade, eu acabei reescrevendo e retirando a expressão regular para validar - eu já tinha reescrito, mas não tinha publicado uma nova versão ainda. Ela, em combinação com o número válido com dígitos extras, é que causava o problema.

Também corrigi outro erro após a publicação, então por favor, utilize a versão 0.4.1 - https://www.nuget.org/packages/Maoli/0.4.1

**Comment by potchy** [comment]
Beleza, muito obrigado!
