### ISSUE TITLE
NetCore compatibility

### ISSUE THREAD

**Issue by evandro-santos** [aueda/maoli#3]
Hi,

I've had some compatibility warnings by using this library on my netcore project.

Is it compatible with netcore project?

**Comment by aueda** [comment]
Hi Evandro,

It wasn’t.

I started porting to .NET Standard a few years ago but I didn’t get a chance to look back.

Also, .NET Core and .NET Standard were in their beginning and the tooling wasn’t that great back then. So I submitted my feedback to Microsoft and stop working in this port.

But, these days, two years after the first release, the .NET Standard is more mature, and well documented. Also, the tooling was greatly improved so I don’t need to work around any issues anymore.

Today I released the version 0.3, which implements .NET Standard and it is .NET Core compatible, so it should work with your .NET Core project.

Here is the link to this release on NuGet: https://www.nuget.org/packages/Maoli/0.3.0

Please update your project and let me know if you have any issues.

Thank you,

Adriano
